### ISSUE TITLE
[SR-12907] `swift test` fails to run with segmentation fault when invoking a method defined/declared in a C based target

### ISSUE THREAD

**Issue by swift-ci** [swiftlang/swift-package-manager#4542]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-12907      |
   |Radar             | None         |
   |Original Reporter | sergiocampama (JIRA User)      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | Package Manager    |
   |Labels            | Bug        |
   |Assignee          | @aciidb0mb3r      |
   |Priority          | Medium      |

   

   md5: 53daa548a7615278a50dda97448ffd2b

  </details>

**Issue Description:**

To repro, on a macOS machine run \`swift test\` on the master branch of <https://github.com/apple/swift-llbuild2>

 

the method that creates the issue is \`blake3_hasher_update\`

**Comment by grynspan** [comment]
This issue may still be valid but there's not enough information to investigate at this time. `blake3_hasher_update` does not appear to be present in the repo and I don't see a commit hash or branch name in the issue description.

If this issue is still occurring, please reopen and let us know updated reproduction steps. Sorry for the delay!

**Comment by grynspan** [comment]
Dug a bit further and `blake3_hasher_update()` is defined in another repo, https://github.com/BLAKE3-team/BLAKE3. That repo does not appear to use XCTest as far as I see.
