### ISSUE TITLE
directoryURL is missing from the Target protocol in the PackagePlugin APIs

### ISSUE THREAD

**Issue by jakepetroules** [swiftlang/swift-package-manager#8001]
### Is it reproducible with SwiftPM command-line tools: `swift build`, `swift test`, `swift package` etc?

- [X] Confirmed reproduction steps with SwiftPM CLI. The description text _must_ include reproduction steps with either of command-line SwiftPM commands, `swift build`, `swift test`, `swift package` etc.

### Description

The `directoryURL` property was added to all of the concrete Target implementations, such as SwiftSourceModuleTarget, ClangSourceModuleTarget, and so on, but not to the base protocol itself.

This means you need a bunch of conditional casts when trying to access the directoryURL in a package plugin.

**Comment by maximkrouk** [comment]
Facing the same issue right now

### Environment:

- Xcode 20.0.1
- Swift 6.2
- swift-tools-version: 6.0
- Package also contains Package@swift-5.9.swift

### Compilation:

- `⚠️ target.directory` produces no warnings (deprecated: 6.1)
- `⚠️ target.directory.string` produces a warning (deprecated: 6.0)
- `❌ target.directoryURL` produces an error (available: 6.1)

### Workaround:

Unfortunately I couldn't find a way to setup conditional compilation based on `swift-tools-version` that is used to compile the plugin, but since [`Path` conforms to `CustomStringConvertible`](https://github.com/swiftlang/swift-package-manager/blob/4ac168de369187f79afb7d34d00c2b9e392b33be/Sources/Runtimes/PackagePlugin/Path.swift#L132) it's possible to silence the warning with

```swift
String(describing: target.directory) // ✅
```

> [!NOTE]
> _Accordingly to sources it **is fixed** and shouldn't be reproducible with `swift-tools-version: 6.1`, so this comment is just a workaround specifically for `swift-tools-version: 6.0`. Though it would be cool if someone from SPM team would share how to set up conditional compilation_
